# Generated by Django 3.1.3 on 2022-02-24 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220127_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('image', models.ImageField(upload_to='job/images/')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 2, 24, 13, 16, 34, 150220, tzinfo=utc))),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('pickup', 'Pickup'), ('droping', 'Droping'), ('complete', 'Complete'), ('canceled', 'Canceled')], default='creating', max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
