# Generated by Django 3.1.3 on 2022-03-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220225_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pickup_address',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='pickup_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='pickup_phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
