# Generated by Django 3.1.3 on 2022-03-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220305_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='drop_address',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='drop_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='drop_phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
